### ISSUE TITLE
How is the closeness between items defined in the network diagram?

### ISSUE THREAD

**Issue by Lucyaaaaaaaa** [X-lab2017/open-digger#1041]
How is the closeness between items defined in the network diagram?

**Comment by frank-zsy** [comment]
In the network diagram, the relationship weight of each developer and repo is calculated based on `activity` index.

If user A and user B are active on the same repo R, and the activity is `Act_ar` and `Act_br`, then the relationship weight by this repo will be `(Act_ar * Act_br)/(Act_ar + Act_br)`. So the weight of A and B will depend on all the repos that they are both active on, so it will be `sum_{r}{(Act_ar * Act_br)/(Act_ar + Act_br)}`.

It is the same for developers.

**Comment by Lucyaaaaaaaa** [comment]
@frank-zsy Thank you for your reply. The following is my understanding, I do not know whether it is correct? Developer A and developer B only worked together on repo1 and repo2, the activity of developer A and developer B on these two repos is actA1, actA2, actB1, actB2. Then the closeness of developers A and B is equal to (actA1*actB1)/(actA1+actB1)+(actA2*actB2)/(actA2+actB2). 
One more question,do you think a developer's teamwork competency can be measured by the closeness with other developers?

**Comment by frank-zsy** [comment]
Yes, your understanding is right about global closeness.

For teamwork competency, I prefer the in-project collaboration network rather than global network. In the in-project network, we can you issue and pull request as the collaborating unit. This is a more detailed network model, if developer A and developer B are active on same issue or pull request, then we can think they have a collaborate relationship.

Actually we use this network to evaluate the influence or contribution of developers in a single repo. If you are considering teamwork competency, you may consider the author of the issue or pull request too. In my opinion, if other developers are willing to interact with you on your issue or pull request, then your teamwork competency is fine, but if other developers do not want to interact on your issue or pull request, maybe there are something wrong here.

**Comment by frank-zsy** [comment]
I will close the issue for now, and please feel to reopen this issue if you have more to discuss on this topic or fire another issue.
