### ISSUE TITLE
How to identify where a IssueCommentEvent log came from

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#1043]
In our dataset, IssueCommentEvent logs  can present a PR comment or a Issue comment. How to identify them quickly?

**Comment by frank-zsy** [comment]
It depends on what you want to implement, the basic logic I can think of is to use other event to identify it like:

![image](https://user-images.githubusercontent.com/8512426/201302330-b1fd70f0-7348-4e2e-aec5-094db2dcf144.png)

If the open and close event related to IssueCommentEvent's issue_number is PullRequestEvent then it is a PR comment, otherwise is an Issue comment.

If you what to find out the count of IssueCommentEvent from PR in OpenDigger, you can do this:

![image](https://user-images.githubusercontent.com/8512426/201303155-de3f149a-98a7-4a26-a334-f4e865071049.png)

**Comment by xgdyp** [comment]
Thanks! We use the same way~
