### ISSUE TITLE
[Question] Why does OpenDigger not provide corresponding metrics for some projects in OpenLeaderboard

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#1107]
Hi @frank-zsy, when I set filter items to `project`, `openrank`,`china`,`month = 2017/02` in [Open LeaderBoard](https://open-leaderboard.x-lab.info/), I find the project ranked 298th is [openresty/openresty-systemtap-toolkit](https://github.com/openresty/openresty-systemtap-toolkit), but I cant find all repo metrics provided by OpenDigger for it.

eg: when I visit https://oss.x-lab.info/open_digger/github/openresty/openresty-systemtap-toolkit/activity.json, it will show nothing.

is it normal?

**Comment by zhicheng-ning** [comment]
One of my current [tasks](https://github.com/X-lab2017/od-api/issues/4) is to crawl the ***repo names*** from all the OpenLeadBoard lists for `projects`, and then use OpenDigger to get all the metrics for those projects.I met this problem that OpenDigger not provide corresponding metrics for some projects in OpenLeaderboard.

**Comment by frank-zsy** [comment]
It is a proper result due to our export policy.

For OpenLeaderboard:
- The export task is https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/open_leaderboard.ts
- As set the [`limit to -1`](https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/open_leaderboard.ts#L275), we will generate all data for any labeled project in OpenLeaderboard, that's why you can find the repo in the ranking list.

But there is a difference for metrics data, for metrics detail metrics data:
- The export task is https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/monthly_export.ts
- As we use `gh_export_repo` table to decide which repos to export and [init the table with all the repos with a history monthly OpenRank > e](https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/monthly_export.ts#L28-L42), so not all the repos are exported with metrics data on GitHub.
- And for `openresty/openresty-systemtap-toolkit` which has only 44 issues and 20 pull requests, the OpenRank of it only reach 1.8 in 2016.11, so it is not in the `gh_export_repo` table which means we will not export metrics data for it.

So if you find some repos without metrics data, you can just skip them because they are not relatively active during its life time.

Or I can add all labeled repos into the export table too, both ways look good to me.

**Comment by zhicheng-ning** [comment]
Thanks for your explain:smile:I hope you can add all labeled repos into the export tableIf it's not too much work for you.

**Comment by frank-zsy** [comment]
Of course, I have added them into the table and export repo count come from 556,561 to 585,324 and export user count come from 374,640 to 374,667. The data will upload to OSS next month.
