### ISSUE TITLE
[Feature] Enrich the metrics documentation

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#1180]
### Description

Currently, we provide data interfaces for metrics and have an at-a-glance table to show the demos and the implementation code. I think it would be better to provide the relevant links where we discuss and explain the details of the metrics, serving as documentation.

For example, we should provide the relevant issue links for CHAOSS metrics, and blog/article links for activity and OpenRank.

**Comment by xiaoya-yaya** [comment]
I will update the README later If there is no objection.

**Comment by frank-zsy** [comment]
That is great, IMO, I think we should update the website of OpenDigger, add description and implementation parameters for each metrics, then we can link the `From` column in README to the website page rather than original CHAOSS page.

In each page of the metrics, we can add following information:

- Metric definition
- Code reference
- Parameters we use
- CodePen demo to consume the data

**Comment by frank-zsy** [comment]
This would be a huge update of OpenDigger website, I will refactor the structure of the website and add some examples about how to write a doc for metrics and indices, then communities can help us to refine the website.

/self-assign

**Comment by xiaoya-yaya** [comment]
Great! I will follow up after the structure is refactored.
