### ISSUE TITLE
[question] the 'groupBy' parameter problem of the 'getRepoOpenrank' function

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/open-digger#1279]
### Description

I can use the following method to get the top 10 openrank databases.
![image](https://user-images.githubusercontent.com/29674550/235927288-a8fa8c69-e43f-43d7-bf41-dc89276bbdf7.png)

But when I add the `groupBy` parameter, the openrank from other domains will also be counted, such as big_data, cloud_native. 
![image](https://user-images.githubusercontent.com/29674550/235929237-b136d172-9e17-418e-89c3-0b3e64062227.png)

If I want to get the openrank of each subdomain under the database domain, how should I choose the parameters here?

Thanks for your reply!

**Comment by PureNatural** [comment]
A similar question.

![image](https://user-images.githubusercontent.com/29674550/235939990-bfedc94a-0c60-4432-8ed4-0f1b5066afce.png)
The above method can get the results for `application_software` domain.

If I want to get the openrank of each domain under the `application_domain`, how should I choose the parameters here?

**Comment by frank-zsy** [comment]
Thanks for the report, actually this is a bug for group by function with when grouping by labels.

The reason is that in this [line of SQL](https://github.com/X-lab2017/open-digger/blob/7bec3a654930e9f7d16be3053a5825da33304db2/src/metrics/basic.ts#L291), I used two `arrayJoin` to get id and name for label data since some repos may labeled by multiple labels at same time. I thought this SQL will give a corresponding id and name columns but it doesn't.

Just like the image shows:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/8512426/236364935-5ecd4ad3-1e73-492a-a280-b15e281b7c47.png">

The rows with red rect is the rows expected to return, but it returns more since `arrayJoin` gives a multiply of two arrays.

And after that, group by id column will give a random result for name and the openrank result is also multiplied by `n` times with `n` is the array length of the label.

I still can not think of a proper way to fix this right now.

**Comment by frank-zsy** [comment]
Just find a way to generate the corresponding `id` and `name` column by tuples with `arrayJoin`, I will fix this soon.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/8512426/236473915-b7b97425-a12d-42a5-b774-53baaf4b0226.png">

/self-assign

**Comment by frank-zsy** [comment]
`Tuple` can be used to generate the columns for corresponding id and names, but with another aggregation function in the SQL, ClickHouse throws an error about the `items` column.

I opened an issue in ClickHouse repo and wait for the response from the community. https://github.com/ClickHouse/ClickHouse/issues/49583

**Comment by frank-zsy** [comment]
@PureNatural I will fix the bug by #1288 , since the maintainer of ClickHouse reply my issue and give a solution.

And return of other label is still right because some repos may also have other `Tech-1` level label like `cloud_native` or `big_data`, so you can filter the result to get the data you want just like this:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/8512426/237058684-28f3670f-e481-4821-b4cf-ebec71ce5077.png">

Is this fit your requirement?
