### ISSUE TITLE
[Bug] the `updatedAt` value in certain users' meta.json lagged behind repos'

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-digger#1364]
### Current Behavior

The user `tyn1998`'s (cache disabled):

<img width="1920" alt="image" src="https://github.com/X-lab2017/open-digger/assets/32434520/8035bb3e-1d91-4130-8500-cccc52ebd91f">

Repos' (and other users'):
<img width="1920" alt="image" src="https://github.com/X-lab2017/open-digger/assets/32434520/be36d9da-007b-438e-8f0e-91bc0749cbec">

### Expected Behavior

All `updatedAt` fields of users' meta files should be in the same month.

### Any Additional Comments?

I even tried in another browser but also found [tyn1998' meta file](https://oss.x-lab.info/open_digger/github/tyn1998/meta.json) has a `createdAt` equals to 2023-07-01

**Comment by frank-zsy** [comment]
It is really strange, do you know any other account with a wrong `updatedAt` field?

**Comment by frank-zsy** [comment]
The bug is caused by the code: https://github.com/X-lab2017/open-digger/blob/bbb2e955dc65aea8e377a2070e01081b728c3772/src/cron/tasks/monthly_export.ts#L296 .

The code uses `date` as `updatedAt` field but the `date` is last month but not now, so all the orgs and users with export repos will be affected, that's why @tyn1998 is affected but not @frank-zsy . I will fix this soon and update the data.
