### ISSUE TITLE
[Question] Why does the same repository have two different IDs in the clickhouse? 

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger#1415]
### Description

When attempting to query the "repo_id" by "repo_name" in the "gh_events" table, I noticed that the same repository has multiple IDs, as shown in the image below. 
I would like to ask what the reason for this and which ID should be used to represent the “repo_id” for this repository.

![image](https://github.com/X-lab2017/open-digger/assets/78625977/6d50fd59-7a5c-47aa-a589-9c5fa57504dc)

![image](https://github.com/X-lab2017/open-digger/assets/78625977/e7aa2c56-fe8c-4a93-8f70-5106a67fd456)

![5f3903108ff4cd5faf984ea88fee7fa](https://github.com/X-lab2017/open-digger/assets/78625977/00f88df9-a01d-42b3-8db6-4aecb1f1d86a)

**Comment by frank-zsy** [comment]
In the GitHub events log, one repo ID may have multiple different repo names and one repo name also may have multiple different IDs. The reason is that:
- If I created a repo with name `a/b`, then deleted the repo and recreated a repo called `a/b`, then `a/b` will have two different IDs with same name.
- If I created a repo with name `a/b`, then changed the name of the repo to `a/c`, then the ID will have two different repo names.
To determine which ID or name to use depends on what you need, in most common scenario you may use the most recent ID or name, you can use `argMax` to get the ID or name first and use it after.

**Comment by Peng99999** [comment]
I got it. Thanks !
