### ISSUE TITLE
[Idea] 2023 China Open Source Annual Report

### ISSUE THREAD

**Issue by wj23027** [X-lab2017/open-digger#1421]
### Description

2023 China Open Source Annual Report follows a structure similar to the previous year, consisting of four sections: 

- 2023 Open Source Chronology
- Questionnaire
- Data
- Commercialisation

We welcome your suggestions for each section to enhance the report further. Your input is highly appreciated as it will contribute to the report's overall improvement.

- Previous Year's Report: https://kaiyuanshe.feishu.cn/wiki/wikcnUDeVll6PNzw900yPV71Sxd

**Comment by mahongweichina** [comment]
In the process of writing the report, some intermediate data is generated. For example, the status of the foundation project was represented using the company's situation in the 2022 report, while in the 2021 report, it was represented using the project's situation. I believe it is acceptable to represent it using the company's situation, making the project's situation an intermediate data. I hope that similar intermediate data can also be made available in other public ways.

Additionally, not all methods have been publicly disclosed during the calculation process. For example, the specific method for confirming which repositories belong to which companies is not fully disclosed. I hope that, as much as possible, this information can be made public so that others can help improve the methods.

**Comment by mahongweichina** [comment]
The situation regarding community and technology trends is constantly changing, but we don't know what these changes entail. Contributor migration can reflect such trends. I suggest using the current algorithm as a foundation to provide a method for visualizing human migration trends.

**Comment by frank-zsy** [comment]
> In the process of writing the report, some intermediate data is generated. For example, the status of the foundation project was represented using the company's situation in the 2022 report, while in the 2021 report, it was represented using the project's situation. I believe it is acceptable to represent it using the company's situation, making the project's situation an intermediate data. I hope that similar intermediate data can also be made available in other public ways.

We can design the structure of the report to show the information developers and companies really care, we also produce the data from OpenDigger in JupyterNotebook first like [2021 report](https://github.com/X-lab2017/open-digger/blob/master/notebook/China_open_source_report_2021.ipynb) and [2022 report](https://github.com/X-lab2017/open-digger/blob/master/notebook/China_open_source_report_2022.ipynb). Even some data may not included in the final report but we can still produce the data and put into the notebook.

> Additionally, not all methods have been publicly disclosed during the calculation process. For example, the specific method for confirming which repositories belong to which companies is not fully disclosed. I hope that, as much as possible, this information can be made public so that others can help improve the methods.

As shown in the notebooks above, actually the data all come from OpenDigger and the company information are also public from the first day of OpenDigger. You can find all the repositories and companies relationships in the [companies label data](https://github.com/X-lab2017/open-digger/tree/master/labeled_data/companies), actually there are companies keep their repositories updated for OpenDigger, like [Alibaba](https://github.com/X-lab2017/open-digger/issues?q=is%3Aissue+author%3Aalibaba-oss), [Ant Group](https://github.com/X-lab2017/open-digger/issues/956), [FitCloud](https://github.com/X-lab2017/open-digger/issues/1234) and etc. So welcome to update the data by opening issue and we will update the data for you for any company.

**Comment by mahongweichina** [comment]
> > Additionally, not all methods have been publicly disclosed during the calculation process. For example, the specific method for confirming which repositories belong to which companies is not fully disclosed. I hope that, as much as possible, this information can be made public so that others can help improve the methods.
> 
> As shown in the notebooks above, actually the data all come from OpenDigger and the company information are also public from the first day of OpenDigger. You can find all the repositories and companies relationships in the [companies label data](https://github.com/X-lab2017/open-digger/tree/master/labeled_data/companies), actually there are companies keep their repositories updated for OpenDigger, like [Alibaba](https://github.com/X-lab2017/open-digger/issues?q=is%3Aissue+author%3Aalibaba-oss), [Ant Group](https://github.com/X-lab2017/open-digger/issues/956), [FitCloud](https://github.com/X-lab2017/open-digger/issues/1234) and etc. So welcome to update the data by opening issue and we will update the data for you for any company.

Perhaps there is a more effective approach to determine the company affiliation of a repository or organization based on the company with the highest number of contributors to the repository. Typically, the majority of contributors come from their respective companies. I acknowledge that this method may not be entirely precise, but when combined with manual effort, it can yield satisfactory results. What do you think of this? Thank you @frank-zsy .

**Comment by frank-zsy** [comment]
@mahongweichina This could be a method to determine the company affiliation of a repository or organization, but actually the developers' affiliation is even a more challenge work than the former one. How can we determine the contributors company information? I know for some projects in Alibaba, the majority of the contributions are from external developers rather than internal ones, so the result would be really hard to use as a solid proof of the company affiliation.

**Comment by mahongweichina** [comment]
> @mahongweichina This could be a method to determine the company affiliation of a repository or organization, but actually the developers' affiliation is even a more challenge work than the former one. How can we determine the contributors company information? I know for some projects in Alibaba, the majority of the contributions are from external developers rather than internal ones, so the result would be really hard to use as a solid proof of the company affiliation.

I agree that determining the contributors' company information is a challenge. We can attempt to determine it based on the company and email information in their profiles, although this method is not perfect. The majority of contributions on some projects come from external developers rather than internal ones. However, these external developers represent various different companies, and the number of developers from a single external company is generally not greater than the number of internal developers from a single company.

**Comment by frank-zsy** [comment]
@mahongweichina Agreed, the diversity of contributors is quite important for the community, actually OpenDigger also published the this as [contributor email suffixes](https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/contributor_email_suffixes.json) metric data. You can easily find out the email suffix of contributors in a community by this metric as a index of diversity.
