### ISSUE TITLE
[Feature] OpenRank algorithm SDK

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#1431]
### Description

We now like the openRank algorithm very much and hope to use the openRank algorithm to implement an integration system: [KToken](https://github.com/kaiyuanshe/KToken). 

I don't know whether openRank provides relevant SDK now, so it is convenient to calculate the relevant score.

**Comment by bifenglin** [comment]
OpenRank is currently undergoing continuous improvement and optimization. Because it requires comprehensive data, if you are interested, you can directly obtain the pre-calculated OpenRank values from the opendigger project or simply use the PageRank algorithm based on the networkx library for calculation. We will replace it once we have completed the optimization.

**Comment by stevending1st** [comment]
> OpenRank is currently undergoing continuous improvement and optimization. Because it requires comprehensive data, if you are interested, you can directly obtain the pre-calculated OpenRank values from the opendigger project or simply use the PageRank algorithm based on the networkx library for calculation. We will replace it once we have completed the optimization.

@bifenglin Thanks

**Comment by frank-zsy** [comment]
@stevending1st  The metrics has been exported, please refer to the document: https://open-digger.cn/docs/user_docs/intro#%E6%8C%87%E6%A0%87%E4%BD%BF%E7%94%A8 .

The data will be in `community_openrank.json` file and the inspect web page also published at https://open-digger.cn/community_openrank_leaderboard .

Feel free to use the data and any issues in the future are welcomed.
