### ISSUE TITLE
[Bug] Tow Demo Link are the same

### ISSUE THREAD

**Issue by bluejeams** [X-lab2017/open-digger#1535]
### Current Behavior

When I clicked the OpenRank and Activity Demo, it seemed display the same page, only got the OpenRank results even choose the Activity Demo.

Here is the screenshot for above operation:

![Bug Report-01](https://github.com/X-lab2017/open-digger/assets/30719712/a7b9beb6-ef3f-458f-b4cf-c42bedda9598)
![Bug Report-02](https://github.com/X-lab2017/open-digger/assets/30719712/cd125770-1471-4709-a45f-8b5613ce1ec1)

**Comment by frank-zsy** [comment]
@bluejeams Thanks for the report, actually we use a single demo pen for activity, openrank and bus factor metrics since they share the same chart format. We are using `type` param in URL to distinguish the different metrics. The demo code is broken and has been fixed, you should see the right chart right now.
