### ISSUE TITLE
Rename the project to OpenDigger

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-digger#494]
As the host siad that the name of this project will be _OpenDigger_. （源力掘醒）

What kinds of things we should do before change the project name ?  or just change it~  :-)

For example, after change the name, the repo link in the pdf version of the report also changed, right ?

**Comment by frank-zsy** [comment]
If we want to rename the project, we need to:
- Rename the repo on GitHub
- Change description in docs
- Change repo config for Hypertrons to adapt new name

If we do not occupy the old name then we don't need to update the URL in PDF report because the old URL will redirect to new URL automatically.

**Comment by frank-zsy** [comment]
closed by #545
