### ISSUE TITLE
[bug] The GitHub Analysis Report with something wrong(Missing newline)

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#507]
There is a missing newline character, where between ` table. ` and `| Rank `, and you can find this place by searching `table. | Rank |`, on this [page](http://www.x-lab.info/github-analysis-report/#/report). This bug caused the Markdown table to fail to render normally.
I tried to fix this bug, but the webpage file was not found in this repo. Not sure if this file exists elsewhere than on this github repository.
thx.

**Comment by frank-zsy** [comment]
Thanks for the the bug report. And actually we directly use this [file](https://github.com/X-lab2017/github-analysis-report/blob/master/docs/report.md) to render on the website. The source file is [here](https://github.com/X-lab2017/github-analysis-report/blob/master/REPORT_TEMPLATE.md) in the template file, the bug may not caused by a missing new line but "/" instead of "|" in the table header line. And we will update later for the new architecture and we fill fix this too.

**Comment by stevending1st** [comment]
Thank you for your hard work.

**Comment by frank-zsy** [comment]
The file has been removed.
