### ISSUE TITLE
[Feature] how to use the Issues and the Discussions

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#638]
I need to know what kind of issues should be discussed in issues and what kind of issues should be discussed in Discussions.
If you have any relevant suggestions or regulations, please give them in the README, top issues, and top discussions.

**Comment by will-ww** [comment]
At this time all of the things disccused in the Issue, and maybe we can design a plan to manage it.

For example, issues are more related to tasks of development, so I convert this issue #771  to the [disciason ](https://github.com/X-lab2017/open-digger/discussions/778?converting=1)

@frank-zsy

**Comment by frank-zsy** [comment]
I am not quite sure about this for 2 reasons:

- For early stage project, there are not too many issues, separate issues and discussions to two places makes it hard to track for developers since like OSSChat bot can not sync discussion into WeChat.
- I really want to use data to evaluate developer work and give some money to participants, but as discussion is a relatively new feature of GitHub, we can not get discussion data automatically right now, it is not friendly for statistics.

**Comment by will-ww** [comment]
OK, I see. Let's me think how to handle this problem. 

For example, as the issue and Discussions can be transformed each other. So, we can always discuss a topic with a issue first, and when the issue is closed, it can be transformed to discussion for further open  discussing. If the issue transfor event data can be collectied, it can even enrich the statistic data.

At this time, issue is sure the dominant way for duscussion. The best way is for waiting GitHub to relase the Discussion API which I am sure if the Discussion become more and more popular.

**Comment by frank-zsy** [comment]
After one and half a year practice, I think only use issue for discussion is enough for OpenDigger.

**Comment by will-ww** [comment]
> After one and half a year practice, I think only use issue for discussion is enough for OpenDigger.

+1
