### ISSUE TITLE
How to resolve governance requirements of some communities conveniently?

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#813]
Now more and more groups, like Mulan community and Alibaba Group, recognize OpenDigger and they also want to improve their governance level by OpenDigger.

Recent days, Mulan wants to get  a report for the first quarter of 2022. Although I can handle it myself at present, there will be more and more such needs in the future. Can we design a solution gracefully to provide services to these organizations?

**Comment by frank-zsy** [comment]
I think there are severals things we can do here.

- We may need to add Mulan community data into OpenDigger first under `community` label and all the projects should be organized as `Project` rather than simple `repo` and `org`.
- We can create a notebook which will be updated quarterly for Mulan community and add what they need into the notebook.
- In the future, we may also create cron tasks to generate data periodically and launch a new project to demonstrate the data like an HTML report or dashboard.

**Comment by gymgym1212** [comment]
Sure, the issue is #814

**Comment by frank-zsy** [comment]
As Mulan community data and dashboard are both completed, we can close for now.
