### ISSUE TITLE
Filter out bot accounts

### ISSUE THREAD

**Issue by antfu** [X-lab2017/open-digger#835]
Should filter out bot accounts from the leaderboard 

<img width="761" alt="image" src="https://user-images.githubusercontent.com/11247099/167783262-67504a32-54df-4db6-8f14-1e6f6fbb1235.png">

**Comment by frank-zsy** [comment]
@antfu Thanks you for issue. Actually we deliberately keep the bot accounts for following reasons:

- We want developers to know about the most popular GitHub Apps so they can try them out later. And we can move them into an individual rank list.
- We can filter out the GitHub Apps accounts since they all ends with `[bot]`, but it is hard to filter out the robots accounts which use GitHub token and API to interact with GitHub like [snyk-bot](https://github.com/snyk-bot), [direwolf-github](https://github.com/direwolf-github) and etc. Or we should keep a labeled data list to record this kind of accounts?

> BTW, big fan of yours and also a [contributor](https://github.com/antfu/vue-minesweeper/pull/16) to your minesweeper project~

**Comment by gymgym1212** [comment]
ooooohhh, alive antfu

**Comment by antfu** [comment]
Maybe a new filter "Applications" or "Bots" after the developer one? And yes I guess for bot accounts we might need to maintain a list.

**Comment by frank-zsy** [comment]
Sure, could you tack on this one? @gymgym1212

**Comment by gymgym1212** [comment]
> Sure, could you tack on this one? @gymgym1212

I'm OK. Do just use the rule of containing 'bot' in login to detect bot?

**Comment by frank-zsy** [comment]
> I'm OK. Do just use the rule of containing 'bot' in login to detect bot?

I will filter the bot account from the rank list in OpenDigger, but maybe we should add a new list for GitHub Apps on the website.

**Comment by frank-zsy** [comment]
Bot account has been removed from the rank list for current data. We may add new list for GitHub Apps in the future.
