### ISSUE TITLE
关于项目活跃度排名的疑问

### ISSUE THREAD

**Issue by zhangliqiang** [X-lab2017/open-digger#898]
您好，
请教个问题，为什么排名第9的各项指标都比排名第8的高，但活跃度分数更低？
![image](https://user-images.githubusercontent.com/6850939/176804728-9fd20792-6c99-4588-8c17-628fc9888b49.png)

**Comment by frank-zsy** [comment]
Thanks for the feedback, the activity index is calculate due to [this SQL](https://github.com/X-lab2017/open-digger/blob/master/src/metrics/activity_openrank.ts#L80), so the activity is not just sum all the events but also take participants into account by calculate square root for every developer. That is activity index tends to give a higher score to a bigger community rather than a small community with more events.As shown in the image below, `PaddlePaddle/PaddleOCR` has more than twice participants numbers then `milvus-io/milvus` in 2022-5 and that is the reason why its activity index is higher.

---

感谢反馈，活跃度指标是通过该 [SQL](https://github.com/X-lab2017/open-digger/blob/master/src/metrics/activity_openrank.ts#L80) 进行计算的，其并非简单的事件加权和，而同时通过对每个开发者的活跃度取平方根的方式将项目中的参与人数也作为一个因素引入，即活跃度指标会倾向于参与人数较多，而非少数开发者较活跃的项目。如下图所示，2022 年 5 月中，`PaddlePaddle/PaddleOCR` 项目的参与人数是 `milvus-io/milvus` 的两倍多，这也是为什么其活跃度更高的原因。

<img width="768" alt="image" src="https://user-images.githubusercontent.com/8512426/176810033-7a10d217-f8b8-4463-9719-26736d1802b0.png">

**Comment by zhangliqiang** [comment]
Got it, thanks.
Maybe it would be better if the participants number is visible.
